backend:
  # name: git-gateway
  name: github
  repo: addisonschultz/nurturedideas
  branch: next

media_folder: static
public_folder: ./

site_url: https://nurtured-ideas.com
display_url: https://nurtured-ideas.com

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  # Site Metadata
  - name: site
    label: "Site"
    editor:
      preview: false
    files:
      - label: "Metadata"
        name: "about"
        file: "src/metadata/site.json"
        create: true
        format: json-frontmatter
        fields:
          - { label: Bio, name: bio, widget: text }
          - name: heroYoutubeVideos
            label: Hero Youtube Videos
            label_singular: Video
            widget: "list"
            fields:
              - { name: youtubeId, label: Youtube ID, widget: "string", hint: "Just the Youtube ID (eg. QB6P6soNmys)" }
  # Artists
  - name: artists
    label: "Artists"
    label_singular: "Artist"
    folder: src/artists
    create: true
    editor:
      preview: false
    format: json-frontmatter
    extension: json
    slug: "{{artistName}}"
    fields:
      - { name: artistName, label: Artist Name, widget: "string" }
      - { name: image, label: Image, widget: "image" }
      - { name: bio, label: Bio, widget: "text" }
      - {
          name: website,
          label: Website,
          widget: "string",
          required: false,
          default: "",
        }
      - {
          name: facebook,
          label: Facebook,
          widget: "string",
          required: false,
          default: "",
        }
      - {
          name: twitter,
          label: Twitter,
          widget: "string",
          required: false,
          default: "",
        }
      - {
          name: instagram,
          label: Instagram,
          widget: "string",
          required: false,
          default: "",
        }
      - {
          name: spotify,
          label: Spotify,
          widget: "string",
          required: false,
          default: "",
        }
      - {
          name: soundcloud,
          label: Soundcloud,
          widget: "string",
          required: false,
          default: "",
        }
      - {
          name: appleMusic,
          label: Apple Music,
          widget: "string",
          required: false,
          default: "",
        }
      - {
          name: tiktok,
          label: TikTok,
          widget: "string",
          required: false,
          default: "",
        }
      - name: releases
        label: Releases
        label_singular: release
        widget: "list"
        fields:
          - { name: releaseName, label: Name, widget: "string" }
          - { name: releaseDescription, label: Release Description, widget: "text", required: false, default: "" }
          - { name: image, label: Image, widget: "image" }
          - {
              name: releaseDate,
              label: Release Date,
              widget: "datetime",
              dateFormat: "DD.MM.YYYY",
              format: "DD.MM.YYYY",
              timeFormat: false,
            }
          - { name: preOrderLink, label: Pre-Order Link, widget: "string", required: false, default: "" }
          - { name: link, label: Link, widget: "string" }
          - name: trackListing
            label: Track Listing
            label_singular: Track
            widget: "list"
            fields:
              - { name: trackName, label: Track Name, widget: "string" }
              - { name: trackDuration, label: Track Duration, widget: "string", hint: "ex. 3:05" }
  # Releases
  - name: releases
    label: "Releases"
    label_singular: "Release"
    folder: src/releases
    create: true
    editor:
      preview: false
    format: json-frontmatter
    extension: json
    slug: "{{releaseName}}"
    fields:
      - { name: releaseName, label: Release Name, widget: "string" }
      - { name: releaseDescription, label: Release Description, widget: "text", required: false, default: "" }
      - { name: artistName, label: Artist Name, widget: "string" }
      - {
          name: releaseDate,
          label: Release Date,
          widget: "datetime",
          dateFormat: "DD.MM.YYYY",
          format: "DD.MM.YYYY",
          timeFormat: false,
        }
      - { name: preOrderLink, label: Pre-Order Link, widget: "string", required: false, default: "" }
      - { name: link, label: Link, widget: "string" }
      - { name: image, label: Image, widget: "image" }
      - name: trackListing
        label: Track Listing
        label_singular: Track
        widget: "list"
        fields:
          - { name: trackName, label: Track Name, widget: "string" }
          - { name: trackDuration, label: Track Duration, widget: "string", hint: "ex. 3:05" }
  # Resources - Interviews
  - name: interviews
    label: "Interviews"
    label_singular: "Interview"
    folder: src/interviews
    create: true
    editor:
      preview: false
    slug: "{{interviewName}}"
    fields:
      - { name: interviewName, label: Interview Name, widget: "string", hint: "ex. Nurtured018" }
      - {
          name: interviewReleaseDate,
          label: Release Date,
          widget: "datetime",
          dateFormat: "DD.MM.YYYY",
          format: "DD.MM.YYYY",
          timeFormat: false,
        }
      - { label: 'Blog post content', name: 'body', widget: 'markdown' }